[package]
name = "esolang-ide"
version = "1.0.0"
edition = "2024"
authors = ["iAeternus <https://github.com/iAeternus>"]
description = "An IDE for esoteric programming languages"
license = "MIT"

[package.metadata.packager]
before-packaging-command = "cargo build --release"
identifier = "com.esolang.ide"
formats = ["nsis"]
resources = ["config/"]
name = "EsolangIDE"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
config = "0.15.19"
eframe = "0.33.2"
egui = "0.33.2"
egui_code_editor = "0.2.20"
encoding_rs = "0.8.35"
rfd = "0.15.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
thiserror = "2.0.17"
